### ISSUE TITLE
Error validation message

### ISSUE THREAD

**Issue by socbaysky** [rgasch/filament-extended-starter-kit#10]
![image](https://user-images.githubusercontent.com/5350936/202966188-4bc01d61-b4c3-426a-b49e-5baefbf2d867.png)

**Comment by rgasch** [comment]
I don't think this is part of the packages which ship with the starter kit. Did you build this yourself?

**Comment by socbaysky** [comment]
> I don't think this is part of the packages which ship with the starter kit. Did you build this yourself?

nope I just use minValue method of Input Masking here: https://filamentphp.com/docs/2.x/forms/fields#input-masking
Please help me!

**Comment by rgasch** [comment]
Please use this forum for such questions: https://github.com/filamentphp/filament/discussions
