### ISSUE TITLE
How to disable registration page?

### ISSUE THREAD

**Issue by socbaysky** [rgasch/filament-extended-starter-kit#4]
How to disable registration page?

**Comment by rgasch** [comment]
Try setting the *enable_registration* field to false in *config/filament-breezy.php*. So: 

```
enable_registration => false
```

Please report back to confirm that this works.

**Comment by socbaysky** [comment]
> Try setting the _enable_registration_ field to false in _config/filament-breezy.php_. So:
> 
> ```
> enable_registration => false
> ```
> 
> Please report back to confirm that this works.

i tried and working 👍
