### ISSUE TITLE
404 not found Home link on homepage

### ISSUE THREAD

**Issue by socbaysky** [rgasch/filament-extended-starter-kit#5]
After login, access http://127.0.0.1:8000/ , you can see Homepage url, that link 404 not found

**Comment by rgasch** [comment]
Can you please be more specific? Does the homepage not work? Or something else?

**Comment by socbaysky** [comment]
Please follow step by step:
1, Login success
2, access http://127.0.0.1/ -> you can see Home url at top right conner
3, click to Home link -> 404 not found

**Comment by rgasch** [comment]
Fixed in 1.0.4. Thank you for reporting.
